api/urls.py
from django.urls import path
from rest_framework import routers
from django.conf.urls import include
from api import views

app_name = 'api'

router = routers.DefaultRouter()
router.register('customers', views.CustomerViewSet)
router.register('carwashes', views.CarwashViewSet)
router.register('orders', views.OrderViewSet)


urlpatterns = [
    path('', include(router.urls)),
]

carwash/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from api.views import GoogleLogin
from rest_framework.authtoken.views import obtain_auth_token


urlpatterns = [
    path('accounts/', include('allauth.urls')),
    path('rest-auth/google', GoogleLogin.as_view(), name='google_login'),
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('auth/', obtain_auth_token),
    path('', include('main.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from main import views as views


app_name = 'main'

urlpatterns = [
    path('customer/<int:pk>/', views.CustomerDetailView.as_view(), name='customer'),
    path('customers/', views.CustomerListView.as_view(), name='customers'),
    path('customer/create/', views.CustomerCreateView.as_view(), name='customer-create'),
    path('customer/<int:pk>/update/', views.CustomerUpdateView.as_view(), name='customer-update'),
    path('customer/<int:pk>/delete/', views.CustomerDeleteView.as_view(), name='customer-delete'),
    path('carwashes/', views.CarwashListView.as_view(), name='carwashes'),
    path('map/', views.CarwashMapView.as_view(), name='map'),
    path('carwash/create/', views.CarwashCreateView.as_view(), name='carwash-create'),
    path('carwash/<int:pk>/', views.CarwashDetailView.as_view(), name='carwash'),
    path('carwash/<int:pk>/update/', views.CarwashUpdateView.as_view(), name='carwash-update'),
    path('carwash/<int:pk>/delete/', views.CarwashDeleteView.as_view(), name='carwash-delete'),
    path('carwashes/carwash-search/', views.carwash_autocomplete, name='carwash-search'),
    path('orders/', views.OrderListView.as_view(), name='orders'),    
    path('order/create/', views.OrderCreateView.as_view(), name='order-create'),
    path('order/<int:pk>', views.OrderDetailView.as_view(), name='order'),
    path('order/<int:pk>/delete/', views.OrderDeleteView.as_view(), name='order-delete'),
    path('customer-autocomplete/', views.CustomerAutocomplete.as_view(), name='customer-autocomplete'),
    path('carwash-autocomplete/', views.CarwashAutocomplete.as_view(), name='carwash-autocomplete'),
    path('map_data/<int:pk>/', views.map_data, name='map-data'),
]

carwash/templates/order/create.html
{% extends "__base.html" %}

{% block container %}
<div class="card">
    <div class="card-header">
        <h5 class="card-title">Create an order</h5>
    </div>
    <div class="card-body">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit" class="btn btn-success">Create</button>
        </form>
        {{ form.media }}
    </div>
</div>
{% endblock %}

carwash/templates/order/delete.html
{% extends "__base.html" %}
{% block container %}
<div class="card">
    <div class="card-header">
        <h5 class="card-title">Delete Order #{{object.id}}</h5>
    </div>
    <div class="card-body">
        <form method="post">
            {% csrf_token %}
            <div class="alert alert-warning" role="alert">
                Are you sure you want to delete <strong>{{ object.name }}</strong> ?
            </div>
            <button type="submit" class="btn btn-danger">Delete</button>
        </form>
    </div>
</div>
{% endblock %}

carwash/templates/order/detail.html
{% extends "__base.html" %}
{% block container %}

<div class="card">
    <div class="card-header">
        <h5 class="card-title">Order Details #{{object.id}}</h5>
    </div>
    <div class="card-body">
    <dl class="row">
      <dt class="col-sm-3">Carwash</dt>
      <dd class="col-sm-9">{{ object.carwash }}</dd>
      <dt class="col-sm-3">Customer</dt>
      <dd class="col-sm-9">{{ object.customer }}</dd>
      <dt class="col-sm-3">Order date</dt>
      <dd class="col-sm-9">{{ object.order_date }}</dd>
      <dt class="col-sm-3">Car body</dt>
      <dd class="col-sm-9">{{ object.car_body }}</dd>
      <dt class="col-sm-3">Interior cleaning</dt>
      <dd class="col-sm-9">{{ object.interior_cleaning }}</dd>
    </dl>

    </div>
</div>

{% endblock %}

carwash/templates/order/orders.html
{% extends "__base.html" %}

{% block container %}
<a class="btn btn-outline-secondary" href="{% url 'main:order-create' %}" role="button"> Create new </a>
<table class="table">
    <tr>
        <thead class="thead-light">
            <tr>
                <th scope="col">Carwash</th>
                <th scope="col">Customer</th>
                <th></th><th></th>
            </tr>
        </thead>
        <tbody>
            {% for i in object_list %}
            <tr>
                <td>{{i.carwash}}</td>
                <td>{{i.customer}}</td>
                <td><a class="btn btn-outline-info" href="{{ i.get_absolute_url }}" role="button"> Open </a></td>
                <td><a class="btn btn-outline-danger" href="{% url 'main:order-delete' i.pk %}" role="button"> Delete </a></td>
            </tr>
            {% endfor %}
        </tbody>
</table>

{% endblock %}