api/urls.py
from django.urls import path
from rest_framework import routers
from django.conf.urls import include
from api import views

app_name = 'api'

router = routers.DefaultRouter()
router.register('customers', views.CustomerViewSet)
router.register('carwashes', views.CarwashViewSet)
router.register('orders', views.OrderViewSet)


urlpatterns = [
    path('', include(router.urls)),
]

carwash/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from api.views import GoogleLogin
from rest_framework.authtoken.views import obtain_auth_token


urlpatterns = [
    path('accounts/', include('allauth.urls')),
    path('rest-auth/google', GoogleLogin.as_view(), name='google_login'),
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('auth/', obtain_auth_token),
    path('', include('main.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from main import views as views


app_name = 'main'

urlpatterns = [
    path('customer/<int:pk>/', views.CustomerDetailView.as_view(), name='customer'),
    path('customers/', views.CustomerListView.as_view(), name='customers'),
    path('customer/create/', views.CustomerCreateView.as_view(), name='customer-create'),
    path('customer/<int:pk>/update/', views.CustomerUpdateView.as_view(), name='customer-update'),
    path('customer/<int:pk>/delete/', views.CustomerDeleteView.as_view(), name='customer-delete'),
    path('carwashes/', views.CarwashListView.as_view(), name='carwashes'),
    path('map/', views.CarwashMapView.as_view(), name='map'),
    path('carwash/create/', views.CarwashCreateView.as_view(), name='carwash-create'),
    path('carwash/<int:pk>/', views.CarwashDetailView.as_view(), name='carwash'),
    path('carwash/<int:pk>/update/', views.CarwashUpdateView.as_view(), name='carwash-update'),
    path('carwash/<int:pk>/delete/', views.CarwashDeleteView.as_view(), name='carwash-delete'),
    path('carwashes/carwash-search/', views.carwash_autocomplete, name='carwash-search'),
    path('orders/', views.OrderListView.as_view(), name='orders'),    
    path('order/create/', views.OrderCreateView.as_view(), name='order-create'),
    path('order/<int:pk>', views.OrderDetailView.as_view(), name='order'),
    path('order/<int:pk>/delete/', views.OrderDeleteView.as_view(), name='order-delete'),
    path('customer-autocomplete/', views.CustomerAutocomplete.as_view(), name='customer-autocomplete'),
    path('carwash-autocomplete/', views.CarwashAutocomplete.as_view(), name='carwash-autocomplete'),
    path('map_data/<int:pk>/', views.map_data, name='map-data'),
]

carwash/templates/__base.html
<!DOCTYPE html>
<html>
<head>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <link rel="stylesheet" href="/resources/demos/style.css">
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>{% block title %}Carwash{% endblock %}</title>
  {% load mapbox_location_field_tags %}
  {% location_field_includes %}
  {% block css %}
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  {% endblock %}
  <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css"
   integrity="sha512-xodZBNTC5n17Xt2atTPuE1HxjVMSvLVW9ocqUKLsCC5CXdbqCmblAshOMAS6/keqq/sMZMZ19scR4PsZChSR7A=="
   crossorigin=""/>
  <script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"
  integrity="sha512-XQoYMqMTK8LvdxXYG3nZ448hOEQiglfqkJs1NOQV44cWnUrBc8PkAOcXy20w0vlaXaVUearIOBhiXZ5V3ynxwA=="
  crossorigin=""></script>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
  {% block extra_js %}{% endblock %}
</head>
<body>

  {% block navbar %}
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">       
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'main:carwashes'%}">Carwashes</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'main:orders'%}">Orders</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'main:customers'%}">Customers</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'main:map'%}">Map</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  {% endblock %}

  <div class="container mt-4">
  {% block container %}
  {% endblock %}
  </div>
</body>
</html>