api/urls.py
from django.urls import path
from rest_framework import routers
from django.conf.urls import include
from api import views

app_name = 'api'

router = routers.DefaultRouter()
router.register('customers', views.CustomerViewSet)
router.register('carwashes', views.CarwashViewSet)
router.register('orders', views.OrderViewSet)


urlpatterns = [
    path('', include(router.urls)),
]

carwash/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from api.views import GoogleLogin
from rest_framework.authtoken.views import obtain_auth_token


urlpatterns = [
    path('accounts/', include('allauth.urls')),
    path('rest-auth/google', GoogleLogin.as_view(), name='google_login'),
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('auth/', obtain_auth_token),
    path('', include('main.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from main import views as views


app_name = 'main'

urlpatterns = [
    path('customer/<int:pk>/', views.CustomerDetailView.as_view(), name='customer'),
    path('customers/', views.CustomerListView.as_view(), name='customers'),
    path('customer/create/', views.CustomerCreateView.as_view(), name='customer-create'),
    path('customer/<int:pk>/update/', views.CustomerUpdateView.as_view(), name='customer-update'),
    path('customer/<int:pk>/delete/', views.CustomerDeleteView.as_view(), name='customer-delete'),
    path('carwashes/', views.CarwashListView.as_view(), name='carwashes'),
    path('map/', views.CarwashMapView.as_view(), name='map'),
    path('carwash/create/', views.CarwashCreateView.as_view(), name='carwash-create'),
    path('carwash/<int:pk>/', views.CarwashDetailView.as_view(), name='carwash'),
    path('carwash/<int:pk>/update/', views.CarwashUpdateView.as_view(), name='carwash-update'),
    path('carwash/<int:pk>/delete/', views.CarwashDeleteView.as_view(), name='carwash-delete'),
    path('carwashes/carwash-search/', views.carwash_autocomplete, name='carwash-search'),
    path('orders/', views.OrderListView.as_view(), name='orders'),    
    path('order/create/', views.OrderCreateView.as_view(), name='order-create'),
    path('order/<int:pk>', views.OrderDetailView.as_view(), name='order'),
    path('order/<int:pk>/delete/', views.OrderDeleteView.as_view(), name='order-delete'),
    path('customer-autocomplete/', views.CustomerAutocomplete.as_view(), name='customer-autocomplete'),
    path('carwash-autocomplete/', views.CarwashAutocomplete.as_view(), name='carwash-autocomplete'),
    path('map_data/<int:pk>/', views.map_data, name='map-data'),
]

carwash/templates/carwash/carwashes.html
{% extends "__base.html" %}
{% load static %}
{% block container %}
<script src="{% static 'js/carwash_search.js' %}" type="text/javascript"></script>
<div class="row no-gutters">
  <div class="col-lg-10 col align-self-end">
    <label class="bmd-label-static" for="carwash_autocomplete_input">Пошук за назвою</label>
    <input id="carwash_search_input" class="form-control" placeholder="Почніть вводити назву..." >
  </div>
    <div class="col-lg-2 col align-self-end">
    <a class="btn btn-outline-secondary w-100" href="{% url 'main:carwash-create' %}" role="button"> Створити нову </a>
  </div>
</div>
<table class="table" id="list"></table>

{% endblock %}

carwash/templates/carwash/create.html
{% extends "__base.html" %}

{% block container %}
<div class="card">
    <div class="card-header">
        <h5 class="card-title">Create a Carwash</h5>
    </div>
    <div class="card-body">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit" class="btn btn-success">Create</button>
        </form>
        {{ form.media }}
    </div>
</div>
{% endblock %}

carwash/templates/carwash/delete.html
{% extends "__base.html" %}
{% block container %}
<div class="card">
    <div class="card-header">
        <h5 class="card-title">Delete Carwash #{{object.id}}</h5>
    </div>
    <div class="card-body">
        <form method="post">
            {% csrf_token %}
            <div class="alert alert-warning" role="alert">
                Are you sure you want to delete <strong>{{ object.name }}</strong> ?
            </div>
            <button type="submit" class="btn btn-danger">Delete</button>
        </form>
    </div>
</div>
{% endblock %}

carwash/templates/carwash/details.html
{% extends "__base.html" %}
{% block container %}

<div class="card">
    <div class="card-header row no-gutters">
        <h5 class="card-title col-lg-3">Carwash Details #{{object.id}}</h5>
        <a class="btn btn-outline-primary col-lg-1" href="{% url 'main:carwash-update' object.id %}" role="button"> Update </a>
        <a class="btn btn-outline-danger col-lg-1" href="{% url 'main:carwash-delete' object.id %}" role="button"> Delete </a>
    </div>
  <div class="card-body">
    <div class="row align-items-center">
      <div class="col-md-6 ml-auto mr-auto">
        <dl class="row">
          <dt class="col-sm-3">Name</dt>
          <dd class="col-sm-9">{{ object.name }}</dd>
          <dt class="col-sm-3">Foundation date</dt>
          <dd class="col-sm-9">{{ object.foundation_date }}</dd>
          <dt class="col-sm-3">E-mail</dt>
          <dd class="col-sm-9">{{ object.email }}</dd>
          <dt class="col-sm-3">Website</dt>
          <dd class="col-sm-9">{{ object.website }}</dd>
        </dl>
      </div>
      <div class="col-md-3 ml-auto mr-auto">
        <img src="{{ object.photo.url }}" class="img-fluid">
      </div>
    </div>
  </div>
    
</div>
        

{% endblock %}

carwash/templates/carwash/map.html
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css"
   integrity="sha512-xodZBNTC5n17Xt2atTPuE1HxjVMSvLVW9ocqUKLsCC5CXdbqCmblAshOMAS6/keqq/sMZMZ19scR4PsZChSR7A=="
   crossorigin=""/>
   <!-- Make sure you put this AFTER Leaflet's CSS -->
 <script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"
   integrity="sha512-XQoYMqMTK8LvdxXYG3nZ448hOEQiglfqkJs1NOQV44cWnUrBc8PkAOcXy20w0vlaXaVUearIOBhiXZ5V3ynxwA=="
   crossorigin=""></script>
   <script src="https://code.highcharts.com/highcharts.src.js"></script>
    <style type="text/css">
	.highchart {
    width: 500px;
    height: 200px;
	}
  </style>
 <div id="mapid" style="height:800px"></div>
 <script>


	var mymap = L.map('mapid').setView([50.4508, 30.5223], 10);

	L.tileLayer('https://api.mapbox.com/styles/v1/{id}/tiles/{z}/{x}/{y}?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4NXVycTA2emYycXBndHRqcmZ3N3gifQ.rJcFIG214AriISLbB6B5aw', {
		maxZoom: 18,
		attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors, ' +
			'<a href="https://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, ' +
			'Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
		id: 'mapbox/streets-v11',
		tileSize: 512,
		zoomOffset: -1
	}).addTo(mymap);

var geojsonCollection = {{geojson | safe}}

function onEachFeature(feature, layer) {

    var div = L.DomUtil.create('div', 'highchart');

    layer.bindPopup(div);


	layer.on('popupopen', e => {
        const url = 'http://' + window.location.host + '/map_data/' + feature.id + '/';
        fetch(url)
            .then(response => {
                return response.json();
            })
            .then(data => {
                Highcharts.chart(e.popup.getContent(), {
                    
                    series: [{
                        data: data
                    }]
                });
            })
        
    });
}

L.geoJSON(geojsonCollection, {
    onEachFeature: onEachFeature
}).addTo(mymap);

 </script>

carwash/templates/carwash/update.html
{% extends "__base.html" %}
{% block container %}
<div class="card">
    <div class="card-header">
        <h5 class="card-title">Carwash Update #{{object.id}}</h5>
    </div>
    <div class="card-body">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit" class="btn btn-success">Update</button>
        </form>
        {{ form.media }}
    </div>
</div>
{% endblock %}